### ISSUE TITLE
[Improvement] Propagate error messages from Slack

### ISSUE THREAD

**Issue by cunger** [reshufflehq/reshuffle-slack-connector#4]
When `postMessage` catches an error, it logs the following message:
```
`Slack Connector - postMessage error to channel ${channel}`
```
This does not give any hint about why the request to Slack failed (wrong permissions, non-existing channel, app was not yet invited to channel, etc). 

It would be really helpful, imho, if the connector included the error message from Slack's response (if there is any).

**Comment by zacmos** [comment]
Thank you @cunger for your feedback.
The code is updated now to include the error message.

**Comment by cunger** [comment]
That's great, thanks!
